name: "\U0001F41E Bug report"
description: Crie um relatório para nos ajudar a melhorar o ArapucaJS
labels: ["triagem"]
body:
  - type: markdown
    attributes:
      value: |
        Por favor, leia atentamente a documentação de contribuição antes de criar um relatório de bug
          👉 https://github.com/arapucajs/.github/blob/main/docs/CONTRIBUTING.md

  - type: input
    id: package-version
    attributes:
      label: Versão do pacote
      description: Você pode rodar `npm ls <nome-do-pacote>` para verificar a versão do pacote
      placeholder: Versão do pacote
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Descreva o bug
      description: Uma descrição clara e concisa do que é o bug. Se você deseja fazer uma pergunta, utilize o [fórum de discussões](https://github.com/arapucajs/core/discussions).
      placeholder: Descrição do bug
    validations:
      required: true
  - type: input
    id: reproduction-repo
    attributes:
      label: Repositório de reprodução
      description: Link para o repositório de reprodução que podemos usar para reproduzir o problema
      placeholder: Opcional, mas recomendado
    validations:
      required: false
